import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Braces, Check, ChevronRight, CircleDot, Code2, Database, Github, Menu, Network, Sparkles, X, Zap } from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Remember — Persistent Memory for AI Agents" },
    { name: "description", content: "Open-source memory infrastructure that helps AI agents learn, retrieve relevant context, and keep conversations lightweight." },
    { property: "og:title", content: "Remember — Persistent Memory for AI Agents" },
    { property: "og:description", content: "Intelligent, continuously learning memory infrastructure for AI agents." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: RememberPage,
});

const nav = [["Features","#features"],["How It Works","#how"],["Architecture","#architecture"],["Developers","#developers"],["GitHub","#open-source"]];
const memories = [
  {type:"USER", title:"Name: Mahadi", score:"0.92", x:"8%", y:"12%"},
  {type:"PROJECT", title:"Remember Memory Gateway", score:"0.96", x:"55%", y:"5%"},
  {type:"PREFERENCE", title:"Cloudflare Workers", score:"0.81", x:"67%", y:"52%"},
  {type:"FACT", title:"Uses PostgreSQL", score:"0.88", x:"7%", y:"63%"},
  {type:"CORRECTION", title:"Previous DB → New DB", score:"0.76", x:"38%", y:"72%"},
];

function RememberPage() {
  const [menu, setMenu] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const fn=()=>setScrolled(scrollY>24);fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn); },[]);
  return <main className="relative min-h-screen bg-background text-foreground">
    <div className="pointer-events-none fixed inset-0 z-50 opacity-[.025]" style={{backgroundImage:"url(\"data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.8'/%3E%3C/svg%3E\")"}} />
    <header className={`fixed left-1/2 top-4 z-40 w-[calc(100%-24px)] max-w-6xl -translate-x-1/2 rounded-lg border border-border transition-all ${scrolled?"bg-background/90 shadow-2xl backdrop-blur-xl":"bg-background/55 backdrop-blur-md"}`}>
      <div className="flex h-14 items-center justify-between px-4 lg:px-5">
        <a href="#top" className="flex items-center gap-2 font-display text-lg font-semibold"><Logo/>Remember</a>
        <nav className="hidden items-center gap-7 text-xs text-muted-foreground md:flex">{nav.map(([label,href])=><a key={href} href={href} className="transition-colors hover:text-foreground">{label}</a>)}</nav>
        <a href="#developers" className="hidden items-center gap-2 rounded-md bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground transition hover:brightness-110 md:flex">Get Started <ArrowRight size={14}/></a>
        <button aria-label="Toggle navigation" onClick={()=>setMenu(!menu)} className="p-2 text-foreground md:hidden">{menu?<X/>:<Menu/>}</button>
      </div>
      {menu&&<nav className="grid border-t border-border p-3 md:hidden">{nav.map(([label,href])=><a key={href} href={href} onClick={()=>setMenu(false)} className="rounded px-3 py-3 text-sm text-muted-foreground hover:bg-muted">{label}</a>)}</nav>}
    </header>

    <section id="top" className="relative flex min-h-[94vh] items-center overflow-hidden px-5 pb-20 pt-32">
      <div className="memory-grid absolute inset-0 opacity-20"/><HeroAura/>
      <div className="relative z-10 mx-auto w-full max-w-6xl text-center">
        <div className="mb-8 inline-flex items-stretch overflow-hidden rounded-md border border-primary/25 bg-background/65 text-[9px] font-semibold uppercase tracking-[.16em] backdrop-blur-xl"><span className="flex items-center gap-2 border-r border-primary/20 bg-primary/10 px-3 py-2 text-primary"><span className="status-pulse h-1.5 w-1.5 rounded-full bg-primary"/>System online</span><span className="flex items-center gap-2 px-3 py-2 text-muted-foreground"><Sparkles size={11} className="text-gold"/>Open-source memory gateway</span></div>
        <h1 className="text-balance mx-auto max-w-5xl font-display text-5xl font-semibold leading-[.98] sm:text-7xl lg:text-[96px]">Give Your AI<br/><span className="hero-memory-text">a Memory.</span></h1>
        <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row">
          <a href="#developers" className="group inline-flex h-12 items-center justify-center gap-2 rounded-md bg-primary px-6 text-sm font-semibold text-primary-foreground shadow-[0_0_32px_color-mix(in_oklab,var(--primary)_24%,transparent)] transition hover:-translate-y-0.5">Get Started <ArrowRight size={16} className="transition group-hover:translate-x-1"/></a>
          <a href="#open-source" className="inline-flex h-12 items-center justify-center gap-2 rounded-md border border-border bg-surface px-6 text-sm font-semibold backdrop-blur transition hover:border-primary/40 hover:bg-muted"><Github size={16}/>View on GitHub</a>
        </div>
        <div className="mx-auto mt-12 grid max-w-2xl grid-cols-3 border-y border-border/70 bg-background/25 py-4 backdrop-blur-sm"><HeroMetric label="Captures" value="Useful signals"/><HeroMetric label="Understands" value="What matters"/><HeroMetric label="Returns" value="Right context"/></div>
      </div>
      <div className="absolute bottom-6 left-1/2 hidden -translate-x-1/2 items-center gap-3 text-[9px] uppercase tracking-[.2em] text-muted-foreground sm:flex"><span className="h-px w-10 bg-line"/>Scroll to trace the system<span className="h-1.5 w-1.5 rounded-full bg-primary shadow-[0_0_10px_var(--primary)]"/></div>
    </section>

    <Section id="how" eyebrow="01 / SYSTEM" title="How Remember Works" copy="A quiet intelligence layer between the conversation and the model—learning continuously, returning only what matters.">
      <Pipeline/>
    </Section>

    <Section eyebrow="02 / SIGNAL" title="Less Context. More Continuity." copy="Remember turns sprawling message history into a focused packet of useful memory.">
      <Compression/>
    </Section>

    <Section eyebrow="03 / MEMORY GRAPH" title="Memory, with meaning." copy="Every memory carries type, provenance, and signals that determine when it should return.">
      <MemoryGraph/>
    </Section>

    <section id="features" className="border-y border-border bg-surface/30 px-5 py-28"><div className="mx-auto max-w-6xl"><SectionHead eyebrow="04 / CAPABILITIES" title="Intelligence below the surface." copy="A focused memory layer built around the realities of long-running AI systems."/>
      <div className="mt-14 grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{features.map((f,i)=><article key={f[0]} className="group min-h-56 bg-background p-7 transition hover:bg-surface"><div className="mb-12 flex items-center justify-between"><span className="font-mono text-[10px] text-muted-foreground">0{i+1}</span><CircleDot size={15} className="text-primary opacity-60 transition group-hover:opacity-100"/></div><h3 className="font-display text-lg font-semibold">{f[0]}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{f[1]}</p></article>)}</div>
    </div></section>

    <Section id="architecture" eyebrow="05 / ARCHITECTURE" title="Built to sit in the middle." copy="Remember works across agents, applications, retrieval systems, and tools without pretending to be the entire stack."><Architecture/></Section>

    <section className="border-y border-border px-5 py-28"><div className="mx-auto max-w-6xl"><SectionHead eyebrow="06 / PRINCIPLE" title="Memory isn't storage. It's intelligence." copy="The difference is not how much context you keep. It is whether the right context returns."/>
      <div className="mt-14 grid gap-5 md:grid-cols-2"><Process title="Traditional Context" muted steps={["Conversation","Send everything","Huge context","Expensive / noisy"]}/><Process title="Remember" steps={["Conversation","Understand","Score & store","Retrieve","Relevant context"]}/></div>
    </div></section>

    <Section id="developers" eyebrow="07 / DEVELOPER EXPERIENCE" title="One gateway. Familiar code." copy="Keep your existing chat completion workflow. Add memory without rebuilding the application around it."><Terminal/></Section>

    <Section eyebrow="08 / LIVE RETRIEVAL" title="Continuity, when it counts." copy="A new question arrives. Remember finds the relevant project memory and places it back into context."><LiveDemo/></Section>

    <section className="border-y border-border bg-surface/25 px-5 py-28"><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionHead eyebrow="09 / MCP" title="Memory belongs beside tools." copy="Through MCP, Remember gives an agent access to persistent memory alongside its tools and active session—not in place of them."/><McpMap/></div></section>

    <section id="open-source" className="px-5 py-28"><div className="glass-panel mx-auto grid max-w-6xl overflow-hidden rounded-lg lg:grid-cols-2"><div className="p-8 sm:p-12"><p className="text-xs font-semibold uppercase tracking-[.2em] text-gold">10 / OPEN SOURCE</p><h2 className="mt-5 font-display text-4xl font-semibold sm:text-5xl">Built in the Open.</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Inspect the architecture. Shape the roadmap. Build memory infrastructure with the community.</p><div className="mt-8 grid grid-cols-2 gap-3 text-sm text-muted-foreground">{["GitHub","Documentation","Contribution","Community"].map(x=><div key={x} className="flex items-center gap-2"><Check size={14} className="text-primary"/>{x}</div>)}</div><a href="https://github.com" target="_blank" rel="noreferrer" className="mt-9 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Explore the Repository <ArrowRight size={15}/></a></div><Repo/></div></section>

    <section className="relative overflow-hidden border-y border-border px-5 py-32 text-center"><div className="memory-grid absolute inset-0 opacity-25"/><HeroNetwork compact/><div className="relative z-10 mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-gold">REMEMBER / ONLINE</p><h2 className="text-balance mt-5 font-display text-5xl font-semibold sm:text-6xl">Give Your AI Something to Remember.</h2><p className="mt-5 text-lg text-muted-foreground">Persistent memory for the next generation of AI agents.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="#developers" className="rounded-md bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">Get Started</a><a href="#open-source" className="rounded-md border border-border bg-surface px-6 py-3 text-sm font-semibold">View GitHub</a></div></div></section>
    <footer className="relative overflow-hidden px-5 pb-8 pt-16"><div className="footer-aura absolute inset-x-0 top-0 h-px"/><div className="mx-auto max-w-6xl"><div className="grid gap-12 border-b border-border pb-14 md:grid-cols-[1.5fr_1fr_1fr]"><div><a href="#top" className="inline-flex items-center gap-3 font-display text-xl font-semibold"><Logo/>Remember</a><p className="mt-5 max-w-sm text-sm leading-6 text-muted-foreground">The intelligent memory gateway between your agents and models. Open source, continuously learning, and built for continuity.</p><div className="mt-6 inline-flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.16em] text-primary"><span className="status-pulse h-1.5 w-1.5 rounded-full bg-primary"/>Memory layer operational</div></div><FooterLinks title="Explore" links={[["How it works","#how"],["Capabilities","#features"],["Architecture","#architecture"]]}/><FooterLinks title="Build" links={[["Developer setup","#developers"],["Open source","#open-source"],["GitHub","https://github.com"]]}/></div><div className="flex flex-col justify-between gap-3 pt-6 font-mono text-[9px] uppercase tracking-[.12em] text-muted-foreground sm:flex-row"><span>Open-source AI memory infrastructure</span><span>Remember / 2026</span></div></div></footer>
  </main>
}

function Logo(){return <span className="relative flex h-7 w-7 items-center justify-center rounded-md border border-primary/40 bg-primary/10"><span className="h-2.5 w-2.5 rounded-full border border-primary shadow-[0_0_10px_var(--primary)]"/></span>}
function HeroMetric({label,value}:{label:string;value:string}){return <div className="px-2 text-left sm:px-5"><span className="block font-mono text-[8px] uppercase tracking-[.14em] text-gold">{label}</span><strong className="mt-1 block text-[10px] font-medium text-muted-foreground sm:text-xs">{value}</strong></div>}
function FooterLinks({title,links}:{title:string;links:string[][]}){return <div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-gold">{title}</p><nav className="mt-5 grid gap-3">{links.map(([label,href])=><a key={label} href={href} className="w-fit text-sm text-muted-foreground transition-colors hover:text-primary">{label}</a>)}</nav></div>}
function Section({id,eyebrow,title,copy,children}:{id?:string;eyebrow:string;title:string;copy:string;children:ReactNode}){return <section id={id} className="px-5 py-28"><div className="mx-auto max-w-6xl"><SectionHead eyebrow={eyebrow} title={title} copy={copy}/><div className="mt-14">{children}</div></div></section>}
function SectionHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-gold">{eyebrow}</p><h2 className="text-balance mt-4 font-display text-4xl font-semibold sm:text-5xl">{title}</h2><p className="mt-5 max-w-xl leading-7 text-muted-foreground">{copy}</p></div>}

function HeroNetwork({compact=false}:{compact?:boolean}){const ref=useRef<HTMLDivElement>(null); const paths:[number,number,number,number][]=[[600,360,170,120],[600,360,1020,170],[600,360,1050,510],[600,360,220,570],[600,360,125,330],[600,360,750,630]]; const nodes:[number,number,string][]=[[170,120,"FACTS"],[1020,170,"PROJECTS"],[1050,510,"TOOLS"],[220,570,"SESSIONS"],[125,330,"CONTEXT"],[750,630,"PREFERENCES"]]; return <div ref={ref} onPointerMove={e=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();ref.current.style.setProperty("--mx",`${(e.clientX-r.left-r.width/2)*.025}px`);ref.current.style.setProperty("--my",`${(e.clientY-r.top-r.height/2)*.025}px`)}} className={`pointer-events-auto absolute inset-0 ${compact?"opacity-35":"opacity-70"}`}><svg viewBox="0 0 1200 720" className="h-full w-full transition-transform duration-700" style={{transform:"translate(var(--mx,0),var(--my,0))"}} aria-hidden="true"><defs><radialGradient id="core"><stop stopColor="var(--emerald-bright)"/><stop offset=".3" stopColor="var(--emerald)"/><stop offset="1" stopColor="var(--background)" stopOpacity="0"/></radialGradient><filter id="blur"><feGaussianBlur stdDeviation="7"/></filter></defs><g fill="none" stroke="var(--line)" strokeWidth="1" className="network-line">{paths.map(([x1,y1,x2,y2],i)=><path key={i} d={`M${x1} ${y1} Q${(x1+x2)/2+i*18} ${(y1+y2)/2-i*20} ${x2} ${y2}`}/>)}</g><g className="memory-core"><circle cx="600" cy="360" r="130" fill="url(#core)" opacity=".35"/><circle cx="600" cy="360" r="42" fill="var(--surface)" stroke="var(--emerald)"/><circle cx="600" cy="360" r="12" fill="var(--gold)" filter="url(#blur)"/><circle cx="600" cy="360" r="5" fill="var(--gold)"/></g>{nodes.map(([x,y,l],i)=><g key={l} className="float-node" style={{animationDelay:`-${i*.7}s`}}><circle cx={x} cy={y} r="4" fill="var(--emerald)"/><circle cx={x} cy={y} r="18" fill="none" stroke="var(--line)"/><text x={x} y={y+36} textAnchor="middle" fill="var(--muted-foreground)" fontSize="9" letterSpacing="2">{l}</text></g>)}</svg></div>}
function HeroAura(){return <div className="hero-aura pointer-events-none absolute inset-0" aria-hidden="true"><div className="aura-field"/><div className="aura-horizon"/><svg viewBox="0 0 1200 760" className="absolute inset-0 h-full w-full" preserveAspectRatio="xMidYMid slice"><g className="aura-rings" fill="none" stroke="var(--line)"><ellipse cx="600" cy="370" rx="170" ry="170"/><ellipse cx="600" cy="370" rx="285" ry="285"/><ellipse cx="600" cy="370" rx="430" ry="430"/></g><path className="aura-orbit" d="M130 450 C330 210 870 210 1070 450" fill="none" stroke="var(--emerald)" strokeOpacity=".3"/><path className="aura-orbit aura-orbit-gold" d="M260 560 C450 690 750 690 940 560" fill="none" stroke="var(--gold)" strokeOpacity=".22"/></svg></div>}

function Pipeline(){const nodes=[["AI Agent","Long conversation enters"],["Remember Gateway","Understands and separates signals"],["Memory Engine","Scores relevance · importance · confidence"],["Relevant Context","A compact packet returns"],["AI Model","Useful continuity, less noise"]];return <div className="glass-panel relative overflow-hidden rounded-lg p-4 sm:p-8"><div className="absolute left-10 right-10 top-1/2 h-px bg-line max-lg:hidden"/><div className="grid gap-3 lg:grid-cols-5">{nodes.map((n,i)=><div key={n[0]} className="relative rounded-md border border-border bg-background/80 p-5"><div className={`mb-8 flex h-9 w-9 items-center justify-center rounded border ${i===1||i===2?"border-primary/50 bg-primary/10 text-primary":"border-border text-muted-foreground"}`}>{i===0?<Braces size={16}/>:i===1?<Network size={16}/>:i===2?<Database size={16}/>:i===3?<Sparkles size={16}/>:<Zap size={16}/>}</div><span className="font-mono text-[9px] text-gold">0{i+1}</span><h3 className="mt-2 font-display text-sm font-semibold">{n[0]}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{n[1]}</p>{i<4&&<ChevronRight className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 text-primary lg:block" size={20}/>}</div>)}</div><div className="mt-4 flex flex-wrap gap-2 border-t border-border pt-4">{["Facts","Preferences","Projects","Corrections","Temporary context","Important events"].map(x=><span key={x} className="rounded border border-border bg-muted px-2.5 py-1 text-[10px] text-muted-foreground">{x}</span>)}</div></div>}
function Compression(){const messages=["Previous session summary","Tool results and traces","Long conversation history","Repeated instructions","Outdated context"];const signals=[["Project","Remember","0.94"],["Runtime","Workers","0.89"],["Database","PostgreSQL","0.84"]];return <div className="glass-panel overflow-hidden rounded-lg"><div className="grid md:grid-cols-[1fr_120px_1fr]"><div className="border-b border-border p-6 md:border-b-0 md:border-r md:p-8"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Raw context</p><span className="rounded border border-border px-2 py-1 font-mono text-[9px] text-muted-foreground">100+ messages</span></div><div className="mt-6 space-y-2">{messages.map((message,i)=><div key={message} className="flex items-center gap-3 rounded border border-border bg-background/70 px-3 py-3"><span className="font-mono text-[9px] text-muted-foreground">{String(i+1).padStart(2,"0")}</span><span className="truncate text-xs text-muted-foreground">{message}</span><span className="ml-auto h-1.5 w-1.5 shrink-0 rounded-full bg-muted-foreground/40"/></div>)}</div></div><div className="relative flex min-h-28 items-center justify-center border-b border-border md:min-h-full md:border-b-0 md:border-r"><div className="absolute left-6 right-6 h-px bg-line md:bottom-8 md:left-1/2 md:right-auto md:top-8 md:h-auto md:w-px"/><div className="glow-green relative z-10 flex h-14 w-14 items-center justify-center rounded-full border border-primary/40 bg-background text-primary"><Sparkles size={18}/></div><span className="absolute bottom-3 font-mono text-[8px] uppercase tracking-[.16em] text-primary md:bottom-7 md:left-1/2 md:translate-x-4 md:[writing-mode:vertical-rl]">Extract signals</span></div><div className="p-6 md:p-8"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Memory packet</p><span className="rounded border border-primary/30 bg-primary/10 px-2 py-1 font-mono text-[9px] text-primary">3 signals</span></div><div className="mt-6 space-y-3">{signals.map(([type,value,score])=><div key={type} className="rounded border border-primary/30 bg-primary/5 p-4"><div className="flex items-center justify-between"><span className="font-mono text-[8px] uppercase tracking-[.14em] text-primary">{type}</span><span className="font-mono text-[9px] text-gold">{score}</span></div><p className="mt-2 text-sm font-medium">{value}</p></div>)}</div></div></div><div className="flex items-center justify-between border-t border-border bg-background/35 px-6 py-4 font-mono text-[9px] uppercase tracking-[.12em] text-muted-foreground"><span>Input · 42.8k tokens</span><span className="text-primary">Output · 312 tokens</span></div></div>}
function MemoryGraph(){return <div className="memory-grid glass-panel relative h-[530px] overflow-hidden rounded-lg"><svg className="absolute inset-0 h-full w-full" viewBox="0 0 1000 530" preserveAspectRatio="none"><g stroke="var(--line)" fill="none" className="network-line"><path d="M170 120L610 85L760 320L460 430L170 360Z"/><path d="M170 120L460 430M610 85L170 360"/></g></svg><div className="absolute left-1/2 top-1/2 z-10 flex h-20 w-20 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-gold/50 bg-background shadow-[0_0_50px_color-mix(in_oklab,var(--gold)_18%,transparent)]"><Database className="text-gold"/></div>{memories.map((m,i)=><div key={m.type} className="float-node absolute w-44 rounded-md border border-border bg-background/90 p-3 backdrop-blur" style={{left:m.x,top:m.y,animationDelay:`-${i}s`}}><div className="flex items-center justify-between"><span className="font-mono text-[8px] tracking-[.15em] text-primary">{m.type}</span><span className="h-1.5 w-1.5 rounded-full bg-gold"/></div><p className="mt-3 text-xs font-medium">{m.title}</p><div className="mt-3 flex items-center gap-2 text-[8px] text-muted-foreground"><span>CONFIDENCE</span><span className="text-gold">{m.score}</span></div></div>)}</div>}
const features=[["Intelligent Memory","Store useful information instead of blindly storing whole conversations."],["Context-Aware Retrieval","Retrieve the memories relevant to the conversation happening now."],["Continuous Learning","Learn useful information from each interaction as the relationship evolves."],["Memory Scoring","Evaluate relevance, confidence, importance, stability, and freshness."],["Conflict Handling","Supersede outdated information instead of accumulating contradictions."],["OpenAI-Compatible Gateway","Integrate into familiar AI workflows without a complete rewrite."],["MCP Integration","Bring persistent memory alongside agent tools and sessions."],["BYOK Architecture","Bring your own model provider while Remember operates as the memory layer."],["Developer Friendly","Use a simple API and a workflow designed for builders."]];
function Architecture(){const flow=[["01","OpenCode / Codex Client","Agent request",Code2],["02","Memory Engine","Learn and persist",Database],["03","Retrieval Engine","Find relevant memory",Network],["04","AI Model","Generate with context",Sparkles]];return <div className="memory-grid glass-panel relative overflow-hidden rounded-lg p-5 sm:p-8 lg:p-10"><div className="grid gap-3 lg:grid-cols-4">{flow.map(([number,title,copy,Icon],i)=>{const FlowIcon=Icon as typeof Code2;return <div key={title as string} className="relative"><div className={`relative min-h-40 rounded border p-5 text-left ${i===1||i===2?"border-primary/40 bg-primary/10 glow-green":"border-border bg-background/90"}`}><div className="flex items-start justify-between"><span className="font-mono text-[9px] text-gold">{number as string}</span><FlowIcon size={17} className={i===1||i===2?"text-primary":"text-muted-foreground"}/></div><h3 className="mt-10 font-display text-sm font-semibold sm:text-base">{title as string}</h3><p className="mt-2 text-xs text-muted-foreground">{copy as string}</p></div>{i<flow.length-1&&<div className="flex h-8 items-center justify-center lg:absolute lg:-right-5 lg:top-1/2 lg:z-10 lg:h-auto lg:-translate-y-1/2"><ChevronRight size={20} className="rotate-90 text-primary lg:rotate-0"/></div>}</div>})}</div><div className="mt-7 flex flex-wrap items-center justify-center gap-2 border-t border-border pt-6">{["Facts","Preferences","Context","Sessions","Metadata"].map(x=><span key={x} className="rounded border border-border bg-background/70 px-3 py-1.5 font-mono text-[9px] text-muted-foreground">{x}</span>)}</div></div>}
function Process({title,steps,muted=false}:{title:string;steps:string[];muted?:boolean}){return <article className={`rounded-lg border p-7 ${muted?"border-border bg-muted/30":"border-primary/30 bg-primary/5 glow-green"}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${muted?"bg-muted-foreground":"bg-primary"}`}/><h3 className="font-display text-lg font-semibold">{title}</h3></div><div className="mt-8">{steps.map((x,i)=><div key={x} className="flex items-center gap-4"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded border text-[10px] ${muted?"border-border text-muted-foreground":"border-primary/30 text-primary"}`}>{i+1}</div><span className="text-sm">{x}</span>{i<steps.length-1&&<span className="ml-auto text-muted-foreground">↓</span>}</div>)}</div></article>}
function Terminal(){return <div className="glass-panel overflow-hidden rounded-lg border-primary/20"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-muted-foreground/40"/><span className="h-2.5 w-2.5 rounded-full bg-gold/60"/><span className="h-2.5 w-2.5 rounded-full bg-primary/70"/></div><span className="font-mono text-[9px] text-muted-foreground">remember — zsh</span><Code2 size={14} className="text-muted-foreground"/></div><div className="grid lg:grid-cols-[1.25fr_.75fr]"><pre className="overflow-x-auto p-6 font-mono text-xs leading-7 sm:p-8"><code><span className="text-muted-foreground">$</span> <span className="text-gold">npm install</span> remember{"\n\n"}<span className="text-primary">const</span> response = <span className="text-primary">await</span> client.chat.completions.create({`({\n  model: `}<span className="text-gold">&quot;your-model&quot;</span>{`,\n  messages\n})`}<span className="terminal-cursor ml-1 text-gold">▋</span></code></pre><div className="border-t border-border bg-background/40 p-6 lg:border-l lg:border-t-0">{["Memory detected","Relevant context retrieved","Context optimized","Request forwarded"].map((x,i)=><div key={x} className="flex items-center gap-3 border-b border-border py-3 text-xs"><Check size={13} className="text-primary"/><span>{x}</span><span className="ml-auto font-mono text-[8px] text-muted-foreground">0{i+1}ms</span></div>)}</div></div></div>}
function LiveDemo(){const [active,setActive]=useState(false);return <div className="glass-panel overflow-hidden rounded-lg"><div className="grid min-h-[440px] lg:grid-cols-2"><div className="border-b border-border p-6 lg:border-b-0 lg:border-r"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-muted-foreground">Conversation</p><div className="mt-7 space-y-5"><Bubble user>I'm building Remember, an AI memory gateway.</Bubble><Bubble>Got it — I'll keep that in mind.</Bubble><Bubble user>What project am I building?</Bubble></div><button onClick={()=>setActive(true)} className="mt-7 inline-flex items-center gap-2 rounded-md border border-primary/40 bg-primary/10 px-4 py-2 text-xs text-primary transition hover:bg-primary/15"><Zap size={13}/>Retrieve memory</button></div><div className="relative p-6"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-primary">Remember</p><div className={`mt-7 rounded-md border p-5 transition-all duration-700 ${active?"translate-y-0 border-primary/40 bg-primary/5 opacity-100":"translate-y-3 border-border opacity-35"}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold">Memory Retrieved</span><span className="h-2 w-2 rounded-full bg-primary shadow-[0_0_10px_var(--primary)]"/></div><dl className="mt-5 grid grid-cols-2 gap-4 text-xs"><Stat label="Project" value="Remember"/><Stat label="Type" value="Project"/><Stat label="Confidence" value="0.94"/><Stat label="Relevance" value="0.91"/></dl></div><div className={`mt-5 rounded-md border border-gold/30 bg-gold/5 p-4 text-sm leading-6 transition delay-300 duration-700 ${active?"opacity-100":"opacity-20"}`}>You're building Remember, an AI memory gateway.</div></div></div></div>}
function Bubble({children,user=false}:{children:ReactNode;user?:boolean}){return <div className={`max-w-sm rounded-md border p-4 text-sm leading-6 ${user?"ml-auto border-border bg-muted":"border-primary/20 bg-primary/5"}`}><span className="mb-2 block font-mono text-[8px] text-muted-foreground">{user?"USER":"ASSISTANT"}</span>{children}</div>}
function Stat({label,value}:{label:string;value:string}){return <div><dt className="font-mono text-[8px] uppercase text-muted-foreground">{label}</dt><dd className="mt-1 text-sm text-foreground">{value}</dd></div>}
function McpMap(){return <div className="memory-grid glass-panel relative min-h-[420px] overflow-hidden rounded-lg p-8"><div className="mx-auto w-36 rounded border border-primary/40 bg-primary/10 p-4 text-center text-sm">AI Agent</div><div className="mx-auto h-10 w-px bg-primary"/><div className="grid grid-cols-3 gap-3">{[["Tools",Braces],["Session",CircleDot],["Memory",Database]].map(([x,I])=>{const Icon=I as typeof Braces;return <div key={x as string} className="rounded border border-border bg-background p-4 text-center text-xs"><Icon size={16} className="mx-auto mb-2 text-primary"/>{x as string}</div>})}</div><div className="ml-[83%] h-10 w-px bg-gold"/><div className="ml-auto w-36 rounded border border-gold/40 bg-gold/5 p-4 text-center"><Logo/><p className="mt-2 text-sm">Remember</p></div></div>}
function Repo(){return <div className="border-t border-border bg-background/60 p-6 lg:border-l lg:border-t-0 sm:p-10"><div className="rounded-md border border-border bg-background"><div className="flex items-center gap-2 border-b border-border p-4"><Github size={16}/><span className="text-sm font-semibold">remember / remember</span><span className="ml-auto rounded border border-border px-2 py-1 font-mono text-[8px] text-muted-foreground">PUBLIC</span></div><div className="space-y-1 p-3">{[["src","Memory engine and gateway"],["packages","SDK and integrations"],["examples","Reference implementations"],["README.md","Build AI that remembers"]].map(([a,b],i)=><div key={a} className="grid grid-cols-[1fr_1.5fr_auto] items-center border-b border-border px-2 py-3 text-xs last:border-0"><span className="text-primary">{a}</span><span className="text-muted-foreground">{b}</span><span className="font-mono text-[8px] text-muted-foreground">{i+2}d</span></div>)}</div></div></div>}